version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    groups:
      python-runtime:
        dependency-type: production
        patterns:
          - "*"
      python-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:35"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:50"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    groups:
      container-images:
        patterns:
          - "*"
