FROM otel/opentelemetry-collector-contrib:0.161.0

COPY deploy/otel/azure-monitor-collector.yaml /etc/otelcol-contrib/azure-monitor.yaml
COPY deploy/otel/azure-monitor-blob-collector.yaml /etc/otelcol-contrib/azure-monitor-blob.yaml
COPY deploy/otel/azure-kusto-collector.yaml /etc/otelcol-contrib/azure-kusto.yaml
COPY deploy/otel/azure-kusto-blob-collector.yaml /etc/otelcol-contrib/azure-kusto-blob.yaml

CMD ["--config=/etc/otelcol-contrib/azure-monitor.yaml"]
